# Generated by Django 4.0.4 on 2022-10-16 09:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectBoardBase',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=64, unique=True)),
                ('description', models.CharField(default='', max_length=64)),
                ('creation_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('team_id', models.IntegerField(default=0)),
                ('board_status', models.CharField(choices=[('OP', 'Open'), ('CL', 'Close')], default='OP', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=64, unique=True)),
                ('description', models.CharField(default='', max_length=128)),
                ('user_id', models.IntegerField(default=0)),
                ('creation_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
