# Generated by Django 4.0.4 on 2022-10-16 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_board_base', '0002_task_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectboardbase',
            name='board_status',
            field=models.CharField(choices=[('Open', 'Open'), ('Close', 'Close')], default='Open', max_length=5),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_status',
            field=models.CharField(choices=[('Open', 'Open'), ('In_Progress', 'In_Progress'), ('Complete', 'Complete')], default='Open', max_length=12),
        ),
    ]
