# Generated by Django 4.0.4 on 2022-10-16 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_board_base', '0003_alter_projectboardbase_board_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectboardbase',
            name='board_status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('CLOSE', 'Close')], default='OPEN', max_length=5),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In_Progress'), ('COMPLETE', 'Complete')], default='OPEN', max_length=12),
        ),
    ]
