# Generated by Django 4.0.4 on 2022-10-16 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_board_base', '0004_alter_projectboardbase_board_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectboardbase',
            old_name='board_status',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='task_status',
            new_name='status',
        ),
    ]
