# Generated by Django 4.0.4 on 2022-10-16 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('team_base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBase',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=64, unique=True)),
                ('display_name', models.CharField(default='', max_length=64)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='team', to='team_base.teambase', to_field='name')),
            ],
        ),
    ]
